### ISSUE TITLE
Verification System

### ISSUE THREAD

**Issue by Dame-G** [RSA-Bots/Reppy#20]
**Feature Addition**
  - What is the feature you would like to see added?
    > Linking Discord accounts to Roblox accounts as a form of verification.
  - Why would this be beneficial to add?
    > Linking reputation to individuals directly on the platform.
    > Events like Game Jams would be easier as there would be no need to ask for Roblox usernames.
    > It would prevent banned users from reentry under the same Roblox account, and would allow us to detect new Roblox accounts created just for brigaiding/ban evasion.
    > Enabling the use of commands such as: /whois.
  - Additional context?
    > Restrict unverified users to #commons areas, and do not allow them to answer/ask questions. (As linking a Roblox account will enable them to gain reputation)

**Comment by TinyPandas** [comment]
How do you feel is the best way about handling verification? RoVer handles it via place join or description matching. Place join detection is outside of my realm of experience, as it plays factors from both ends. I can use Roblox's provided endpoints in detecting their description matching immediately.

**Comment by TinyPandas** [comment]
v0.1 removed potential implementation for this.
